import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div ></div>
          
        </div>


        <div >
          <div
            className={styles.card}
          >
          <Image
            className={styles.logo}
            src="/shirt.gif"
            alt="Next.js Logo"
            width={365}
            height={365}
            priority
          />
            <h2 className={inter.className}>
              piece 1
            </h2>
            <h4 className={inter.className}>
              $100
            </h4>
            <p className={inter.className}>
              a really cool 1 of 1 piece!!
            </p>
            
          </div>
        </div>
        <footer>
        <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            >
              <h2 className={inter.className}>powered by cypher labs 🌎
              </h2>
            </a>
          </div>
        </footer>
      </main>
    </>
  )
}
